-- phpMyAdmin SQL Dump
-- version 4.5.4.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Feb 08, 2016 at 12:08 PM
-- Server version: 5.5.44-MariaDB
-- PHP Version: 5.6.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `robotics_2016`
--
CREATE DATABASE IF NOT EXISTS `robotics_2016` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `robotics_2016`;

-- --------------------------------------------------------

--
-- Table structure for table `bios`
--
-- Creation: Feb 06, 2016 at 05:29 PM
--

DROP TABLE IF EXISTS `bios`;
CREATE TABLE IF NOT EXISTS `bios` (
  `bio_ID` int(11) NOT NULL AUTO_INCREMENT,
  `bio_Lang` int(2) NOT NULL,
  `bio_FullName` varchar(50) CHARACTER SET utf8 NOT NULL,
  `bio_GOTName` varchar(50) CHARACTER SET utf8 NOT NULL,
  `bio_TeamID` int(2) NOT NULL,
  `bio_Challenges` text CHARACTER SET utf8 NOT NULL,
  `bio_Experience` text CHARACTER SET utf8 NOT NULL,
  `bio_Image` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`bio_ID`),
  KEY `bio_Lang` (`bio_Lang`),
  KEY `bio_TeamID` (`bio_TeamID`)
) ENGINE=InnoDB AUTO_INCREMENT=94 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Truncate table before insert `bios`
--

TRUNCATE TABLE `bios`;
--
-- Dumping data for table `bios`
--

INSERT INTO `bios` (`bio_ID`, `bio_Lang`, `bio_FullName`, `bio_GOTName`, `bio_TeamID`, `bio_Challenges`, `bio_Experience`, `bio_Image`) VALUES
(2, 0, 'Alex Hayeur', 'Jaddon Bender', 0, 'Finalizing design processes for the robot.', 'Electrical design and electrical systems.', 'AlexHayeur.jpg'),
(3, 0, 'David Dahan', 'Morryn The Butcher (free folk)', 0, 'Remaining within the rules of the competition.', 'Becoming a part of the robotics team and finding out what can be accomplished when great minds combine.', 'DavidDahan.jpg'),
(4, 0, 'Alex Stojda', 'Assollo', 6, 'Coordinating each sub-team in order for them to meet their respective deadlines', 'People are very stubborn and need alot of persuasion to change their views once they are set.', 'AlexStojda(Captain).jpg'),
(5, 0, 'Charlie Tang', 'Yraegarys Dorraeiounos', 2, 'Finding out where the missing closing tag was missing.', 'Learning HTML.', 'CharlieTang.jpg'),
(6, 0, 'Alec Zarow', 'Erock Wendwater', 3, 'To compose music in major instead of minor.', 'I learned a lot about composing and different musical techniques.', 'AlecZarow.jpg'),
(7, 0, 'Natasha Lalonde', 'Natari Sarsfield', 2, 'Learning to work outside my comfort zone with people I do not know.', 'I have learned an incredible amount from coming to Vanier, a new school far away from any of my friends and my community. ', 'NatashaLalonde.jpg'),
(9, 0, 'Jethro "Jet" Roy', 'Keath Tyrell', 0, 'Actually doing stuff that counts', 'I can actually do stuff that counts if I want', 'JethroRoy.jpg'),
(10, 0, 'Stoianovici Cristian Andrei', 'Jon Sto', 0, 'Getting the parts we needed ordered.', 'How to be a mad scientist', 'StoCristian.jpg'),
(11, 0, 'Zixin He', 'Jares Oldflowers', 0, 'Keeping people motivated so that we meet deadlines.', '"It\'s easy to convince people of something, but hard to keep them convinced." - Niccolò Machiavelli', 'ZixinHe(Captain).jpg'),
(13, 0, 'Alexander Spinali', 'Torromir Galadhon', 0, 'Deciding on a final concept for the robot was a huge challenge as a team.', 'I learned some digital design as well as some debating skills to make sure that my ideas were seriously considered.', 'AlexanderSpinali.jpg'),
(14, 0, 'Syeda Nessa', 'Anrea Appleton', 2, 'Learning the web programming and markup languages', 'I learnt how to make a website!', 'SyedaNessa.jpg'),
(15, 0, 'Yuxin Hu', 'Bancey Hayard', 2, 'Trying to complete all the tasks assigned to me quickly and efficiently.', 'Working as a team to build a great website!', 'YuXinHu.jpg'),
(16, 0, 'Daniel Wiktorczyk', 'Erner Worner', 0, 'Becoming first acquainted with the programming code', 'Learning about electrical work!', 'DanielWiktorczyk.jpg'),
(17, 0, 'Daniel lee', 'Rhelmar Carson', 1, 'Trying to come up with new and creative ideas.', 'Helping build and design the kiosk.', 'DanielLee.jpg'),
(18, 0, 'Angela Athanasopoulos', 'Angelys Centyre', 1, 'Trying to summon my artistic abilities to use to make the Kiosk.', 'Drawing is one of the longest learning experience, since I\'ve done it for a long time and I keep learning more all the time.', 'AngelaAthanasopoulos.jpg'),
(20, 0, 'Tian Yue Jiao', 'Gween Thorne', 2, 'Coming on time', 'How to screw screws on a very limited surface (I often screw up).', 'TianYueJiao.jpg'),
(21, 0, 'Jaeeun Lee', 'Sharley Celtigar', 0, 'Working with people whom I don`t know well', 'Gathering various mechanisms to make a robot', 'JaeeunLee.jpg'),
(22, 0, 'Xin Yu Zhang', 'Sharley Celtigar', 2, 'Start learning to code from scratch.', 'Being able to read basic codes.', 'XinYuZhang.jpg'),
(23, 0, 'Nicola Grenon Vinci', 'Nykolaï Blackfyr', 0, 'Unscrew the stuck screws.', 'Overcome the parental attachment of the prototypes we created to destroy them.', 'NicolaGrenonVinci.jpg'),
(24, 0, 'Haritos Kavallos', 'Lord Harryn Ashwood', 4, 'The biggest challenge lies in attempting to balance my involvement as team administrator with the other tasks associated with my job at Fort Vanier.', 'I have learned that plebs certainly enjoy waiting until the last minute to complete their tasks. It seems they enjoy the punishment of working on tight deadlines. ', 'HaritosKavallos.jpg'),
(25, 0, 'Ian Phillips', 'Frenduk Solarus', 3, 'Winter', 'I learned how to operate a boom mic on a movie production set.', 'IanPhilips.jpg'),
(27, 0, 'Jashana Baskaran', 'Kyra Orme', 1, 'Showing up on time ', 'Organization and Team Work', 'JashanaBaskara.jpg'),
(28, 0, 'Paola Petitti', 'Paolari Seaworth', 3, 'The biggest challenge I encountered was deciding what props to use to create foley art.', 'The biggest learning experience would have to be learning how to use the audio recording programs.', 'PaolaPetitti.jpg'),
(29, 0, 'Vanessa Mastropietro', 'Vanessa Mastropietro', 3, 'The biggest challenge I\'ve encountered so far is figuring out what props I can use for foley art', 'My biggest learning experience is the creativity is a key skill to have when working on a video', 'VanessaMastroPietro.jpg'),
(30, 0, 'George Mavroeidis', 'Ando Tarlor', 3, 'Filming in the snow was really challenging.', 'Setting up the cameras and green screens was a nice experience to learn.', 'GeorgeMavroeidis.jpg'),
(31, 0, 'Patrick Walling-Laperriere', 'The Enthusian', 0, 'Coordinating with all the other members and their ideas', 'Measure twice, cut once.', 'PatrickWallingLaperriere.jpg'),
(32, 0, 'Jonathan Cyga', 'Peata Mallark', 3, 'Figuring out what were the biggest challenges I\'ve encountered.', 'My biggest learning experience was in high school when I got into photography and I had to learn everything about photography.', 'JonathanCyga.jpg'),
(33, 0, 'Arjun Rajan', 'AJ the Secret Leader', 0, 'Rulling without anyone finding out.', 'Leading is best left for the leaders.', 'ArjunRajan.jpg'),
(34, 0, 'Massimo Triassi', 'Asneir', 3, 'Learning to manage such a large and enthusiastic team.', 'When we brought the team to a cold forest, it taught me a lot about how hard you can work a team.', 'MassimoTriassi(Captain).jpg'),
(35, 0, 'Evangelos Dimopoulos', 'Aeron Seral', 2, 'Actually having to work on things.', 'attempting to funnel my charisma into work (i failed).', 'EvanDimopolous.jpg'),
(36, 0, 'Jaxon Lin', 'Jain Æðelwine', 0, 'Taking apart and rebuilding the same piece multiple times because we forgot something/it doesn\'t work.', 'Changing the length of a gear belt.', 'JaxonLin.jpg'),
(37, 0, 'Alexander Oxorn', 'The Ox', 3, 'To find where I belong in the team.', 'Learning how to constructively collaborate with other people and share ideas.', 'AlexOxorn.jpg'),
(38, 0, 'Chris Iannotti', 'Roran Rykker', 3, 'Winter and the weather.', 'Video Editing and teamwork.', 'ChrisIanotti.jpg'),
(40, 0, 'Ioana Bruj', 'Ioana "The Immortal"', 2, 'Keeping track of the big picture', 'Learning how to use Blender', 'IoanaBruj.jpg'),
(41, 0, 'Sahar Haidary', '"Saharah Targaryen"', 2, 'Learning to manage my time efficiently. ', 'Learn how to use Blender', 'SaharHaidary.jpg'),
(42, 0, 'Serena Tan', 'The Secret-Keeper', 2, 'Getting to school during winter break.', 'Learning how to use Blender.', 'SerenaTan.jpg'),
(43, 0, 'Melissa Dunn', 'Melisari Frey', 3, 'Finding the right props to create foley.', 'Using the audio recording device', 'MelissaDunn.jpg'),
(44, 0, 'Sabreena Mills ', 'Sabreansa Baratheon ', 3, 'I have had a hard time making time to help out. ', 'Time management is very important, balancing school, work, volunteer work and clubs can be quiet difficult. ', 'SabreenaMills.jpg'),
(45, 0, 'Viveka Anban', 'Ayara Frosher', 3, 'Trying to remember to close all my HTML tags.', 'I learnt how to use a real text editor and not notepad.', 'VivekaAnban.jpg'),
(46, 0, 'Banujan Atputharajah', 'Lord Apu', 2, 'Deciding which technology to use for the website (CSS 3D or WebGL).', 'Working in teams and sharing different ideas.', 'BanujanAtputharajah.jpg'),
(47, 0, 'Ariana Gagnon', 'Aenerya Galmaereon', 1, 'Getting every detail of kiosk finalized and done properly on time.', 'Everything!! There is always something new to learn from the team.', 'ArianaGagnon(Captain).jpg'),
(49, 1, 'Alex Stojda', 'Assollo', 6, 'Coordinné toutes les équipes pour qu’elles puissent respecter leur date limite.', 'Les membres sont pas mal têtus et c’est difficile de leur faire changer les idées.', 'AlexStojda(Captain).jpg'),
(50, 1, 'Alec Zarow', 'Erock Wendwater', 3, 'De composer la musique en majeur au lieu de mineure.', 'Ma plus grande expérience a été que j’ai beaucoup appris par rapport à la composition et aux différentes techniques musicales. ', 'AlecZarow.jpg'),
(51, 1, 'Alexander Spinali', 'Torromir Galadhon', 0, 'C’était un grand défi d’équipe de parvenir à un accord pour le concept final du robot. ', 'J’ai appris comment faire de la conception digitale et j’ai également acquis des compétences de débat afin d’assurer que mes idées soient prises au sérieux. ', 'AlexanderSpinali.jpg'),
(52, 1, 'Alexander Oxorn', 'The Ox', 3, 'Trouver ma place dans l\'équipe.', 'Apprendre à collaborer d\'une manière constructive avec d\'autres personnes et partager des idées.', 'AlexOxorn.jpg'),
(53, 1, 'Alex Hayeur', 'Jaddon Bender', 0, 'Finaliser les processus de conception pour notre robot.', 'Ma plus grande expérience a été la conception électrical et systèmes électricaux. ', 'AlexHayeur.jpg'),
(54, 1, 'Angela Athanasopoulos', 'Angelys Centyre', 1, 'Essayer de convoquer mes capacités artistiques à utiliser pour faire le Kiosk.', 'Le dessin a longuement été une expérience d’apprentissage pour moi vu que je l’ai faite pour longtemps et que je continue toujours d’apprendre. \r\n', 'AngelaAthanasopoulos.jpg'),
(55, 1, 'Ariana Gagnon', 'Aenerya Galmaereon', 1, 'Completer tous les détails de kiosque dans une façon vite et belle.', 'Toute!! Il y a toujours quelque chose de nouveau a apprendre!', 'ArianaGagnon(Captain).jpg'),
(56, 1, 'Arjun Rajan', 'AJ the Secret Leader', 0, 'Faire les décisions sans que personne ne le sache.', 'L\'interligne est préférable de laisser aux dirigeants.', 'ArjunRajan.jpg'),
(57, 1, 'Banujan Atputharajah', 'Lord Apu', 2, 'Décider quelle technologie utiliser pour le site web. (CSS 3D or WebGL).', 'Travailler en équipe et partager des idées.', 'BanujanAtputharajah.jpg'),
(58, 1, 'Charlie Tang', 'Yraegarys Dorraeiounos', 2, 'Apprendre à écrire couleur sans le “u”.', 'Apprendre le HTML.\r\n', 'CharlieTang.jpg'),
(59, 1, 'Chris Iannotti', 'Roran Rykker', 3, 'L’hiver et la météo.', 'La rédaction d’un vidéo et le travail d’équipe.', 'ChrisIanotti.jpg'),
(60, 1, 'Daniel lee', 'Rhelmar Carson', 1, 'Être à l’école pour travailler.', 'Travailler avec le site web ainsi que le kiosque.', 'DanielLee.jpg'),
(61, 1, 'Daniel Wiktorczyk', 'Erner Worner', 0, 'Me familiariser avec le code de programmation.', 'Apprendre par rapport aux travaux électricaux.', 'DanielWiktorczyk.jpg'),
(62, 1, 'David Dahan', 'Morryn The Butcher (free folk)', 0, 'Respecter les règles de la compétition.', 'Devenir membre de l’équipe robotique et découvrir ce qui peut être accomplit.', 'DavidDahan.jpg'),
(63, 1, 'Evangelos Dimopoulos', 'Aeron Seral', 2, 'Devoir faire du travail.', 'Essayer d’intégrer mon charisme dans mon travail. (J’ai échoué)\r\n', 'EvanDimopolous.jpg'),
(64, 1, 'George Mavroeidis', 'Ando Tarlor', 3, 'C’était très difficile de faire le tournage du film dans la neige.', 'J’ai aimé apprendre comment mettre les caméras et écrans verts en place.', 'GeorgeMavroeidis.jpg'),
(65, 1, 'Haritos Kavallos', 'Lord Harryn Ashwood', 4, 'Le plus grand défi est d’essayer de trouver un équilibre entre mon implication comme administrateur d’équipe et entre les autres tâches que j’ai comme employé du Fort Vanier.', 'J’ai appris que les plebes aiment attendre à la dernière minute pour complèter leurs tâches. Ils semblent aimer le stress de travailler avec peu de temps.', 'HaritosKavallos.jpg'),
(66, 1, 'Ian Phillips', 'Frenduk Solarus', 3, 'L’hiver.', 'J’ai appris comment opérer un microphone perche sur un site de production de film.', 'IanPhilips.jpg'),
(67, 1, 'Ioana Bruj', 'Ioana "The Immortal"', 2, 'Garder l’objectif final en tête.', 'Apprendre à utiliser Blender.', 'IoanaBruj.jpg'),
(68, 1, 'Jaeeun Lee', 'Sharley Celtigar', 0, 'Travailler avec des gens que je ne connais pas très bien.', 'Cueillir des mechanismes afin de créer un robot. ', 'JaeeunLee.jpg'),
(69, 1, 'Jashana Baskaran', 'Kyra Orme', 1, 'Être à l’heure.', 'L’organisation et le travail d’équipe.', 'JashanaBaskara.jpg'),
(70, 1, 'Jaxon Lin', 'Jain Æðelwine', 0, 'Démanteler et reconstruire les mêmes espèces parce que nous avons oublié quelque chose ou parce que quelque chose ne fonctionne pas.', 'Changer la longueur d’une ceinture d’engrenage.', 'JaxonLin.jpg'),
(71, 1, 'Jethro "Jet" Roy', 'Keath Tyrell', 0, 'Faire de quoi qui aide pour de vrai.', 'Je peux vraiment faire de quoi qui aide pour de vrai.', 'JethroRoy.jpg'),
(72, 1, 'Jonathan Cyga', 'Peata Mallark', 3, 'Déterminer mes plus grands défis. ', 'Ma plus grande expérience d’apprentissage était au secondaire quand j’ai commencé à faire la photographie et j’ai dû tout apprendre.', 'JonathanCyga.jpg'),
(73, 1, 'Massimo Triassi', 'Asneir', 3, 'Apprendre à gérer une équipe si large et enthousiaste.', 'Quand j’ai apporté l’équipe dans un forêt froid, j’ai beaucoup appris sur la résistance de notre équipe.', 'MassimoTriassi(Captain).jpg'),
(74, 1, 'Melissa Dunn', 'Melisari Frey', 3, 'Trouver les bonnes accessoires pour créer des sons.', 'Utiliser le dipositif d’enregistrement d’audio.', 'MelissaDunn.jpg'),
(75, 1, 'Natasha Lalonde', 'Natari Sarsfield', 2, 'Apprendre à travailler à l’extérieur de ma zone de confort avec des gens qui je ne connais pas.\n', 'J’ai appris l’importance de la proactivité: si on veut que quelque chose se fasse accomplir, on doit donner le coup d’envoi.', 'NatashaLalonde.jpg'),
(76, 1, 'Nicola Grenon Vinci', 'Nykolaï Blackfyr', 0, 'Déviser les vis coincés.', 'Surmonter nos attachments parentaux envers les prototypes que nous avons créés afin d’être capable de les détruire.', 'NicolaGrenonVinci.jpg'),
(77, 1, 'Paola Petitti', 'Paolari Seaworth', 3, 'Le plus grand défi que j’ai eu a été de décider quelles accessoires utilisées pour créer l’art foley. ', 'Ma plus grande expérience d’apprentissage a été d’apprendre à utiliser les programmes d’enregistrement d’audio.', 'PaolaPetitti.jpg'),
(78, 1, 'Patrick Walling-Laperriere', 'The Enthusian', 0, 'Coordonner avec toutes les autres membres ainsi que leurs idées.', 'Mesurer deux fois, couper une fois.', 'PatrickWallingLaperriere.jpg'),
(79, 1, 'Sabreena Mills ', 'Sabreansa Baratheon ', 3, 'J’ai de la difficulté à trouver du temps pour aider.', 'La gestion du temps est très difficile losrqu’on a l’école, le travail, le bénévolat et les clubs.', 'SabreenaMills.jpg'),
(80, 1, 'Sahar Haidary', '"Saharah Targaryen"', 2, 'Apprendre à gérer mon temps efficacement.', 'Apprendre à utiliser Blender.', 'SaharHaidary.jpg'),
(81, 1, 'Serena Tan', 'The Secret-Keeper', 2, 'Aller à l’école durant la pause d’hiver.', 'Apprendre à utiliser Blender.', 'SerenaTan.jpg'),
(82, 1, 'Stoianovici Cristian Andrei', 'Jon Sto', 0, 'Obtenir les pièces dont nous avions besoin commandé.', 'Être un scientifique fou.', 'StoCristian.jpg'),
(83, 1, 'Syeda Nessa', 'Anrea Appleton', 2, 'Je suis nouvelle, alors tout est difficile pour le moment.', 'J’ai appris comment créer un site web.', 'SyedaNessa.jpg'),
(84, 1, 'Tian Yue Jiao', 'Gween Thorne', 2, 'Être à l’heure.', 'Comment viser des vis sur une surface limitée. (Je fais souvent des gaffes) ', 'TianYueJiao.jpg'),
(85, 1, 'Vanessa Mastropietro', 'Vanessa Mastropietro', 3, 'Le plus grand défi que j’ai eu a été de décider quelles accessoires utilisées pour créer l’art foley.', 'Ma plus grande expérience d’apprentissage est parvenu lorsque j’ai réalisé que la créativité est une compétence essentielle à avoir lors de la création d’un vidéo.', 'VanessaMastroPietro.jpg'),
(86, 1, 'Viveka Anban', 'Ayara Frosher', 3, 'Essayant de se souvenir de fermer tous mes balises HTML.', 'J\'appris à utiliser un véritable éditeur de texte et pas notepad.', 'VivekaAnban.jpg'),
(87, 1, 'Xin Yu Zhang', 'Sharley Celtigar', 2, 'Commencer à apprendre à faire le code.', 'Être capable de lire des codes de base.', 'XinYuZhang.jpg'),
(88, 1, 'Yuxin Hu', 'Bancey Hayard', 2, 'Essayer de completer toutes les tâches qui me sont confiées rapidement et efficacement.', 'Travailler en équipe pour construire un excellent site Web!', 'YuXinHu.jpg'),
(89, 1, 'Zixin He', 'Jares Oldflowers', 0, 'Motiver l\'équipe pour respecter les délais.', '"S\'il est aisée de persuader le monde de quelque chose, il est difficile de les affermir dans cette persuasion." - Niccolò Machiavelli', 'ZixinHe(Captain).jpg'),
(90, 0, 'Richard Mondoux', 'Phalos Sefte', 4, 'Learning everyone\'s name', 'Cookies still buy happiness', 'RichardMondoux.jpg'),
(91, 1, 'Richard Mondoux', 'Phalos Sefte', 4, 'Se souvenir des noms de tous les nouveaux membrex', 'Tout le monde aime les biscuits', 'RichardMondoux.jpg'),
(92, 1, 'Andrew Hanichkvosky', 'Alrah', 2, 'Guider le monde pour suivre une programme approprié et faire avancer les taches à temps.', 'Travailler avec de nouvelles librairies JavaScript (flip book) et en essayant de créer une conception adaptée.', 'AndrewHanichkovsky(Captain).jpg'),
(93, 0, 'Andrew Hanichkvosky', 'Alrah', 2, 'Getting everyone to follow a proper schedule and getting things done on time.', 'Working with new javascript libraries (flipbook) and trying to create responsive design.', 'AndrewHanichkovsky(Captain).jpg');

-- --------------------------------------------------------

--
-- Table structure for table `book`
--
-- Creation: Feb 06, 2016 at 05:29 PM
--

DROP TABLE IF EXISTS `book`;
CREATE TABLE IF NOT EXISTS `book` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `book` enum('HOME','VANIER','GAME','ROBOT','JOURNALISM','TEAM','GALLERY','TUTORIAL','SPONSORS') CHARACTER SET latin1 NOT NULL,
  `lang` int(2) NOT NULL,
  `content` longtext CHARACTER SET latin1,
  `subpage` enum('BUILD','KIOSK','VIDEO','WEB') CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `book_id_uindex` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=158 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='stores all text for description pages';

--
-- Truncate table before insert `book`
--

TRUNCATE TABLE `book`;
--
-- Dumping data for table `book`
--

INSERT INTO `book` (`id`, `book`, `lang`, `content`, `subpage`) VALUES
(22, 'VANIER', 0, '	\n<h1>The Tournament</h1>\n\n<p>Fort Vanier is an advanced (post-secondary) educational institution that serves as a stepping stone to the youngsters that wish to access the royal court, on top of offering many noble titles. At first, it was named Fortress Basile-Moreau, but was renamed Vanier Fort in 1970. This fort employs the Westeros Common Tongue (English) and now serves over 6500 squires and young ladies seeking to acquire knowledge in their respective discipline. Vanier was, for a second year in a row and a third year in four years, the host of the CRC blacksmith and spar (robotics) tournament. Thanks to its dynamic mentors and environment, enthusiastic pupils and extraordinary equipage, it was one of the top choices for the organisation. This year, the competition will be held at Montmorency Fort, once again offering a great venue for Pythagorium 2016.', ''),
(23, 'VANIER', 0, '<h1>Programs</h1>\n<p>The institution\'s academic welfare is enhanced through royally-trained servants, resource support, and social and cultural quests. The hallmarks of its programs are intellectually diverse content and children from families all over Westeros. The Fort continues to run full-time pre-court programs and knighthood training programs for a "Diploma of Fort Studies" certification, while the Adult Apprenticeships Tribes (Continuing Education Department) runs septon-approved (credit DCS) and full squire-to-knight (Attestation of College Studies (ACS)) mentorships, as well as small-folk trainings (non-credit) ones.</p>', ''),
(24, 'VANIER', 0, '<h1>VTV</h1>\n<p>VTV is the Fort\'s online pupil-run multimedia network. Based out of Vanier Communications and Commerce Affairs program server, VTV produces both live and pre-recorded intellectual content. The network\'s ideals include strengthening Vanier\'s community network, increasing public internal connections of Vanier Fort, and providing an outlet for users to input their own content. This approach to multimedia content is unique in the Quebec Cegep system, and makes the Fort supremely proud. VTV releases weekly updates to the public via their messenger birds and livestreams of major developments taking place in Fort Vanier so that users can watch the events unfold in real-time with their own eyes. Other VTV components include family intel, departmental profiles, pedagogical activity, award ceremonies, news stories of the Fort, campaigns, artistic projects, activities and much more.</p>', NULL),
(25, 'VANIER', 0, '<h1>Jake\'s Cafe</h1>\n\n<p><img class="left zoom-this" height="180px" src=\'{{img_path}}/jakes.jpg\' alt=\'Jakes\'/>Vanier Fort is proud to announce that under its new policy of healthy food and healthy living standards, a pupil-organized co-op dining-room was inaugurated, with the help of the Borough of Saint-Laurent and Vanier\'s head pupils offering freshly hunted food. Jake\'s Dining is the first CO-OP organization in Westeros Forts, and hopefully the first of many. This initiative truly encompasses Vanier\'s support of pupil initiative, as well as resource management for the approaching winter.</p>', NULL),
(27, 'VANIER', 0, '<h1>Pupil Council (VCSA)</h1>\n\n<p>The Pupil Council (Vanier College Students\' Association (VCSA)) is the Fort\'s biggest association. It is allocated an important budget which permits it to create smaller houses and invest in interesting pupil projects and initiatives, like Jake\'s Dining and Vanier\'s new synthetic field, as well as the Vanier Blacksmith and Spar (Robotics) Association. As its goal is to reach out and answer the pupils\' needs, it is represented purely by the pupils and its projects steer purely towards the pupils\' needs. <img height="110px" src="http://devbana.tk/images/sponsors/vcsa.png" alt="VCSA" style="margin-top: 10px;"/></p>\n', NULL),
(28, 'VANIER', 0, '<h1>Location</h1>\n<p>Vanier Fort</p>\n<p>205.236.144.4</p>\n<p>821, Sainte-Croix avenue, Saint-Laurent</p>\n<p>Montréal, Québec</p>\n<p>H4L 3X9</p>\n<img height=200px src="{{img_path}}/vanierMap.jpg" alt="Vanier">', NULL),
(29, 'VANIER', 1, '<h1>Le Tournoi</h1>\r\n<p>Le fort Vanier est une institution d’éducation avancée qui a permis à de nombreux étudiants à atteindre une occupation prestigieuse dans le court royal. Le collège offre également plusieurs titres nobles. Il était d’abord nommé Forteresse Basile-Moreau, et par la suite, en 1970, Fort Vanier. Ce dernier emploie la langue commune de Westeros (Anglais) et sert présentement 6500 jeunes cavaliers et dames qui cherchent à acquérir des connaissances dans divers disciplines. Vanier a été, en quatre ans, trois fois hôte du tournoi de forgeron et longeron (robotique) de la CRC. Cela a été un des meilleurs choix pour l’organisation grâce aux mentors dynamiques, à l\'environnement paisible, aux étudiants enthousiastes et à l\'extraordinaire équipage du Collège Vanier. Cette année, la compétition aura lieu au fort Montmorency, qui est un endroit également idéal pour Pythagorium 2016.</p>', NULL),
(30, 'VANIER', 1, '<h1>Programmes</h1>\r\n<p>Le bien-être scolaire de cette institution est accentué par les serviteurs royalement entraînés, par le soutien des ressources et par les quêtes sociales et culturelles. Les caractéristiques fondamentales de ses programmes sont le contenu divers ainsi que les élèves venant de partout dans Westeros. Le fort continue d\'exécuter des programmes pré-court à temps plein et des programmes d\'entraînement de chevalerie pour un certificat de “Diplôme d\'étude de fort”, pendant que les tribus des apprentissages d’adultes (Département d’éducation permanente) exécutent des mentorats approuvés par les septons (DCS de crédit) et des mentorats d\'écuyers à chevalier (Attestation d’études collégiales), ainsi que des entraînements mineures (sans-crédit).</p>', NULL),
(31, 'VANIER', 1, '<h1>VTV</h1>\n<p>VTV est le réseau multimédia en ligne du Fort dirigé par les élèves. Basé dans le serveur du programme des affaires de communications et du commerce de Vanier, VTV produit du contenu intellectuel réenregistré ainsi que du contenu enregistré en direct. Les idéaux du réseau inclut le renforcement du le réseau de communauté de Vanier, l’augmentation des connections publiques internes du fort Vanier et le fournissage d’un endroit où les utilisateurs peuvent produire leur propre contenu. Cette approche au contenu multimédia est unique dans le système collégial du Québec et par conséquent, le fort en est extrêmement fier.</p>', NULL),
(32, 'VANIER', 1, '<p> À chaque semaine, VTV met le publique à jour à travers leurs oiseaux messagers et leurs diffusions en direct de développements majeures qui se produisent au fort Vanier pour que les utilisateurs puissent voir les évènements en temps réel. Le VTV inclut aussi des composants de familles, de profiles départementales, des activités pédagogiques, des cérémonies de bourses, des nouvelles du Fort, des campagnes, des projets artistiques, des activités, et beaucoup plus.</p>', NULL),
(33, 'VANIER', 1, '<h1>Café Jake’s</h1>\n\n<p><img class="left" height="180px" src=\'{{img_path}}/jakes.jpg\' alt=\'Jakes\'/>Le fort Vanier est fier d\'annoncer qu’en vertu de la nouvelle politique de nourriture santé et de standards de vie santé, une salle à manger organisée par les élèves a été inaugurée. Cette dernière a été créée avec le soutien des terres de Saint-Laurent et celui des élèves qui offrent de la nourriture cuisinée avec des proies fraîchement chassées. Le café Jake’s est la première organisation COOP dans les forts Westeros et nous espérons qu’elle ne sera pas la dernière. Cette initiative englobe le support que Vanier possède pour ses élèves et elle renforce la gestion des ressources pour l’hiver prochain. </p>', NULL),
(34, 'VANIER', 1, '<h1>Conseil des élèves</h1>\n<p>Le conseil des élèves (Conseil étudiants des élèves Vanier (VCSA)) est la plus grande association du Fort. Ce conseil est alloué un budget important qui lui permet de créer des petits groupes et d’investir dans des projets et des initiatives de disciples, comme le café Jake’s, le nouveau terrain synthétique de Vanier et l’association de forgeron et de longeron Vanier (robotique). Comme l’objectif de ce conseil est de répondre aux besoins des élèves, il est représenté uniquement par les élèves et ses projets existent pour les aider.<img height="110px" src="http://devbana.tk/images/sponsors/vcsa.png" alt="VCSA" style="margin-top: 10px;"/></p>', NULL),
(35, 'VANIER', 1, '<h1>Location</h1>\n\n<p>Vanier Fort</p>\n\n<p>205.236.144.4</p>\n\n<p>821, Sainte-Croix avenue, Saint-Laurent</p>\n\n<p>>Montréal, Québec</p>\n<p>H4L 3X9</p>\n<img height=200px src="{{img_path}}/vanierMap.jpg" alt="Vanier">', NULL),
(36, 'GAME', 0, '<h1>Pythagorium 2016</h1>\r\n<h1>Goal</h1>\r\n<p>It is only by creating the biggest triangle possible with playing pieces that a house can win the great war at Fort Montmorency, all while fending off enemies in order to sit on the Iron Throne of Pythagorium 2016. Their enchanted armor must be able to pick up and place playing pieces in their allotted slots on each end of the playing field, while fending off White Walkers and worrying about their own safety. Each hole can contain more than one piece each, and each piece will bring you closer to victory. However, only the ones in the foreground (the last ones in place) will count towards the multiplier. Aided by teamwork and perseverance, the team with the largest triangle will emerge victorious!</p>', NULL),
(37, 'GAME', 0, '<h1>Team</h1>\r\n<p>This war, like all great wars, will be fought with alliances. The Yellow army and the Blue army, each with two enchanted armors (robots) at their disposal, will be competing in this Game of Triangles. In each round, or heat, the alliances and the enchanted armors will change. Each enchanted armor must try to score as many points as possible for their team, no matter what. </p>', NULL),
(38, 'GAME', 0, '<h1>Playing Pieces</h1>\n<p>The playing pieces that the enchanted armors will be handling are cylindrical floating wood (foam) pieces, of three different lengths: 1 Usurper Length (unit length), 2 UL and 3 UL. They will come in yellow and blue and each team’s enchanted armor will handle those in their color. At the beginning of each wave, each enchanted armor will be allowed to have two playing pieces preloaded. <p>\n<img src="../../images/game/pieces.jpg" class="gameImage">', NULL),
(39, 'GAME', 0, '<h1>Playing Field</h1>\n\n<p>This great war will be fought in a large rectangular field. At the beginning of each round, the enchanted armors must begin in zones of their color, in the corners of the war zone. These zones will change places between the preliminaries and the playoffs, sub-sections of this great war. The scoring panels, situated on either side, are fair game to either team. In the center of the war zone, there will be a revolving door and on the sides, there will be slopes with deadly spikes on which the pieces are pegged. </p>\n<img src="../../images/game/feild.jpg" class="gameImage">', NULL),
(40, 'GAME', 0, '<h1>On Deck </h1>\r\n<p>To begin each round of this strangely organized war, each competing House’s spotter, driver and enchanted armor, clearly identified with their House’s sigil (school name) and numeral motto (competition number), must be prepared in the war zone before the end of the previous round. If the horn signaling the end of the round sounds before the next armies are ready, there will be a penalty assigned to the late armies and the round will begin without them. They will be abandoned to the unforgiving world beyond the war zone and the Wall. During the war, each team must remain within their designated areas around the war zone in order to control their enchanted armor. Once the rounds begin, spotters and drivers cannot step into the war zone or come into contact with any enchanted armors or playing pieces. This war is to be as “safe” as possible.</p>', NULL),
(41, 'GAME', 0, '<h1>In Play  - Rules of War</h1>\r\n<p>If, during the war, an enchanted armor exits the war zone, the Ancient Gods (referees) will replace it where it left. Playing pieces, however, cannot be replaced once they leave the war zone. They are considered out of play for the rest of the round. If any enchanted armor becomes lodged in the revolving door, an Ancient God will replace it in its initial half of the playing field; they will not help any enchanted armor cross to the other side of the field. The enchanted armor must remain in movement, if not it will be considered stuck. Enchanted armors cannot cause any damage to the war zone, the pieces or any other enchanted armors.</p>', NULL),
(42, 'GAME', 0, '<p>Playing pieces can stick out of the slot into which it is inserted, since the entirety of the length will still count towards the score. These pieces can, however, be removed by interfering, rival enchanted armors.  Pieces that are completely inserted cannot be touched. No enchanted armors may enter inside the scoring structure, in air, space, or other.  </p>\n<h1>End of Battle</h1>\n<p>Each wave will last 5 minutes. The war will be efficient. At the end, with the sounding of the buzzer, all enchanted armors must cease all movement. Entrance to the war zone can only occur once the representant Ancient God allows it. </p>', NULL),
(43, 'GAME', 0, '<h1>Scoring</h1>\n<p>At the end of each heat of the war Pythagorium 2016, the value of the spoils of war will be determined. Each enchanted armor must place at least one playing piece into a slot in order to share the score. Each level of the scoring panel will be worth a different amount of points per unit of length: 10 for the first, 20 for the second, 30 for the third and 40 for the fourth. Alliances will also have the opportunity to multiply their points, based on the largest triangle constructed in their color. These triangles must have a outermost layer in the same color and must have a horizontal base with sides of either 2,3 or 4 slots in length. The number of slots used in the base of these triangles will determine the fate of the multiplier.</p>', NULL),
(44, 'GAME', 0, '<p>A 2-slot based triangle will double the value of the spoils, a 3-slot based triangle will triple it, and a 4-slot based triangle will quadruple it. When the preliminary heats come to an end, the two lowest spoil values will be discarded and total spoils values and placements will be determined.</p>\n<img src="../../images/game/score.jpg" class="gameImage">', NULL),
(45, 'GAME', 0, '<h1>Etiquette and Conduct </h1>\r\n<p>This war shall be fought with the uttermost Westerian respect. If the Ancient Gods should catch you exhibiting any non-noble like conduct, a never lifting curse (permanent penalty) will be given. Such conduct includes activities such as attempting to damage another team’s enchanted armor or behaving inappropriately to soldiers or smallfolk (spectators), all of which be judged by the Ancient Gods. There will also be penalties given for leaving any materials or liquids behind at the end of a heat : a junk penalty. A penalty of up to 4 million gold pieces or 4% of the score can be placed if items are still in contact with the enchanted armor when times runs out. </p>', NULL),
(46, 'GAME', 1, '<h1>Pythagorium 2016</h1>\r\n\r\n<h1>Objectif</h1>\r\n<p>Dans le but d’émerger victorieuse de la Grande Guerre du Fort Montmorency, chaque Grande Maison doit viser à construire la structure triangulaire la plus imposante avec les pièces du jeu. Seulement une famille gagnera le trône de Fer. Durant la bataille, l’armure enchantée doit être capable de ramasser et d’insérer les bûches servant de pièces de jeu dans leur fentes allouées aux deux extrémités de la zone de guerre, tout en se protégeant des Marcheurs Blancs. Chaque fente peut tenir plus qu’une bûche, et chaque bûche bien placée apporte la Maison un pas plus près de la victoire. Par contre, seulement les bûches au premier plan (les dernières bûches insérées) comptent pour l’effet multiplicateur. Avec la persévérance et de l’esprit d’équipe, la Maison ayant le plus grand triangle construit à partir des bûches à la fin du jeu emporte la bataille!</p>', NULL),
(47, 'GAME', 1, '<h1>Équipe</h1>\n<p>Cette guerre, comme toutes les grandes guerres, se déroulera entre armées fédérées. L\'armée Jaune et l\'armée Bleu se rivaliseront dans ce jeu de triangles, chacun avec deux armures enchantées (robots) à leur disposition. Lors de chaque affrontement, les alliances et les armures enchantées vont changer. Chaque armure enchantée essayera de marquer autant de points possible pour leur équipe.</p>', NULL),
(48, 'GAME', 1, '<h1>Bûches et pointage</h1>\n<p>Afin que chaque armée marque des points, l’armure enchantée doit saisir des bûches de bois (cylindres de styromousse) de trois différentes longueurs:  1 UL (unité de longueur), 2UL et 3UL. Les bûches seront jaune et bleue, seulement l’armée de la couleur correspondante pourra les utiliser (Armée Jaune =­> bûche jaune). Au début de la vague d\'ennemis, deux bûches sont permises dans les griffes de l’Armure.</p>\n<img src="../../images/game/pieces.jpg" class="gameImage">', NULL),
(49, 'GAME', 1, '<h1>Zone de guerre</h1>\n<p>La grande guerre se déroulera dans un terrain rectangulaire. Au début de chaque tournée, les armures enchantée commenceront dans leur zones de couleurs correspondantes, situées dans les coins du terrain. Ces derniers changeront lors des préliminaires et des play-offs. Les panneaux de points sont situés aux extrémités de la zone de guerre. Enfin, au centre de la zone, il y aura une porte tambour. Des deux cotés de ceci, il y a des pointes mortelles sur lesquelles les pièces seront mises. </p>\n<img src="../../images/game/feild.jpg" class="gameImage">', NULL),
(50, 'GAME', 1, '<h1>Début de l’affrontement</h1>\n<p>Pour débuter chaque affrontement de cette guerre étrangement conçue, le guetteur et l’enchanteur/enchanteresse de chaque Maison doivent être prêts avant la fin du dernier affrontement. Ils doivent aussi s’identifier à l’aide de leur blason (nom d’école) et de leur devise numérique (numéro d’identification), comme toute armée qualifiée. Si le klaxon annonçant la fin de la dernière partie sonne avant que les prochaines armées soient prêtes, ces dernières souffriront d’une pénalité et l’affrontement débutera sans elles. </p>', NULL),
(51, 'GAME', 1, '<p>Les soldats absents seront laissés en dehors de la zone de guerre, loin de leur patrie et de leur royaume. Durant l’affrontement, chaque participant doit demeurer dans leur zone désignée afin de contrôler leur armure enchantée. Une fois que l’affrontement débute, il est interdit d’entrer dans la zone de guerre ou d’entrer en contact avec les armures et/ou les bûches. Cette guerre doit être sécuritaire pour les nobles (et seulement occasionnellement, les paysans). </p>', NULL),
(52, 'GAME', 1, '<h1>Pendant le jeu - règles de la guerre</h1>\r\n<p>Si, durant l’affrontement, une armure enchantée sort de la zone de guerre, les anciens dieux (arbitres) la replaceront là où elle est sortie. Les pièces en jeu, cependant, ne peuvent pas être remplacées une fois qu\'elles quittent le terrain. Elles sont considérées comme hors du jeu pour le reste de la bataille. Si une armure enchantée se loge dans la porte tournante, un Dieu antique la replacera dans son terrain de jeu initial; ils n’aideront aucune armure enchantée à traverser le terrain. Elle doit rester en mouvement, sinon, elle sera considérée bloquée. Les armures enchantées ne peuvent pas causer de dommages à la zone de guerre, aux pièces où à d\'autres armure enchantée. </p>', NULL),
(53, 'GAME', 1, '<p>Les bûches du jeu peuvent dépasser la fente dans laquelle elles sont insérées, car la totalité de la longueur sera toujours pris en compte pour le score. Cependant, des armures enchantées rivales ont la liberté d’enlever ces bûches ressorties. Par contre, les morceaux qui sont complètement insérés sont verrouillés en place et ne peuvent pas être enlevés de leur position. Aucune armure enchantée ne peut entrer à l\'intérieur de la structure de notation, dans l\'air, l\'espace, ou autre.</p>', NULL),
(54, 'GAME', 1, '<h1>Fin de l’affrontement</h1>\r\n<p>Chaque affrontement durera 5 minutes. La guerre sera efficace. Le klaxon de bataille sonnera la fin de l’affrontement. À ce bruit, les armures enchantées doivent cesser tout mouvement. L’accès à la zone de guerre est seulement permis avec l’autorisation de l’ancien dieu responsable.</p>', NULL),
(55, 'GAME', 1, '<h1>Pointage</h1>\r\n<p>À la fin de chaque affrontement de la guerre Pythagorium 2016, une note sera attribuée. Chaque armure enchantée doit avoir placée au moins une bûche dans le but afin d’obtenir une partie du butin de guerre. Chaque niveau du but octroie des valeurs du butin différentes pour chaque unit de longueur de la bûche: 10 pour le premier, 20 pour le deuxième, 30 pour le troisième et 40 pour le quatrième. Chaque équipe aura la possibilité de multiplier leur valeur de butin dépendant de la plus grande triangle formée de leur couleur. </p>', NULL),
(56, 'GAME', 1, '<p>Ces triangles devront comporter une bordure extérieure de leur couleur d’équipe et une base horizontale de soit 2, 3 ou 4 unités de longueur. Celle-ci déterminera la valeur multiplicative de leur butin. Un triangle à base de 2 unités doublera la valeur du butin, un triangle à base de 3 unités triplera la valeur et un à 4 unités la quadruplera. Lors de la fin des vagues préliminaires, les deux butins avec le moins de valeur ne seront pas considérés et la valeur totale du butin et les placements seront calculés.</p>', NULL),
(57, 'GAME', 1, '<img src="../../images/game/score.jpg" class="gameImage">', NULL),
(58, 'GAME', 1, '<h1>Étiquette et conduite</h1>\r\n<p>Cette guerre débute, se déroule, et se conclut selon les normes respectueux de Westeros. Les actions dans le but d’endommager l’armure enchantée d’une autre Maison, le symbole ultime du Foi des Septs, ainsi que le manque de respect envers l’ennemi ou envers les innocents déshonorent le royaume et doivent être punis. La rage des dieux anciens sera terrible et la Maison recevra une malédiction éternelle (pénalité permanente). Laisser des déchets sur la zone de guerre sacrée mènera aussi à une malédiction. Jusqu’à 4 millions de pièces d’or (4% du score) seront ôtées des coffres de la Maison si les déchets sont encore en contact avec l’armure enchantée lors de la fin de la vague.</p>', NULL),
(59, 'SPONSORS', 0, '<h1>Sponsors </h1>\n<p>A big thank you to our sponsors, to whom we owe much of our success. </p>\n\n<h1>Fort Vanier/Vanier College</h1>\n<img style="height: 100px;" src="../../images/sponsors/Vanier.jpg" class="sponsorImage">\n<p>Always ready to help fund school initiatives, Fort Vanier has dedicated much gold to helping the Vanier Blacksmith and Spar (Robotics) Association buy supplies for kiosk and enchanted armor building. Without their continuous help and support, this team would not be half as well equipped for this war.</p>', NULL),
(60, 'SPONSORS', 0, '<h4>Pupil Council/Vanier College Students Association</h4>\n<img style="height: 100px;" src="../../images/sponsors/VCSA.jpg" class="sponsorImage">\n<p>Ever since October 20th 2014, the Vanier College Students’ Association has been financially supporting and sponsoring the Vanier Blacksmith and Spar (Robotics) Association. This year, they are helping fund their works for Pythagorium 2016, being held on February 25th to 27th at Fort Montmorency. The VCSA is an organization that prides itself on its support of student projects and activities. The hard work and dedication that the teams have exemplified throughout the semester and the winter break have made them ideal candidates to be worthy of VCSA funding. </p>', NULL),
(61, 'SPONSORS', 0, '<h1>Team Bana</h1>\n<img style="height: 100px;" src="../../images/sponsors/TeamBana.jpg" class="sponsorImage">\n<p>Team Bana, a group of pupils from Fort Vanier, produces websites and applications for small armies throughout Westeros by using the knowledge and skills that they’ve gained through the Computer Science and Technology program. Their funding and experience has been essential to this great war.</p>', NULL),
(62, 'SPONSORS', 0, '<h1>Rona Pierrefonds</h1>\n<img src="../../images/sponsors/Rona.jpg" class="sponsorImage">\n<p>RONA L’entrepôt Pierrefonds first opened its doors in 2007 and has since been serving its community’s home renovation needs from its location at 3933 Boul. St Charles, Pierrefonds. RONA is your all-in-one stop for hardware, building materials and home renovation products. </p>', NULL),
(63, 'SPONSORS', 1, '<h1>Commanditaires </h1>\n\n<p>Un gros merci à tous nos commanditaires, à qui nous devons notre succès. </p>\n\n<h1>Fort Vanier/College Vanier </h1>\n<img src="../../images/sponsors/Vanier.jpg" class="sponsorImage">\n<p>Toujours prêt à aider fonder des initiatives de l\'école, le fort Vanier a donné beaucoup d’or à l’équipe de forgeron et longeron (robotique) pour qu’ils puissent acheter des provisions pour la construction du kiosque et de l’armure enchantée. Sans leur support et leur aide, cette équipe ne sera sûrement pas aussi preparée. </p>', NULL),
(64, 'SPONSORS', 1, '<h4>Conseils des pupils/Conseil étudiants des élèves Vanier</h4>\n<img src="../../images/sponsors/VCSA.jpg" class="sponsorImage">\n<p>Depuis le 20 octobre 2014, le conseil étudiants des élèves Vanier a aidé à financer les projets de l’équipe de forgeron et longeron (robotique). Cette année, ils les aident à fonder leurs travaux pour Pythagorium 2016, qui se déroulera au fort Montmorency du 25 au 27 février. La VCSA est une organisation qui est fier de supporter les projets et les activités des élèves. Le travail et le dévouement que les équipes ont démontré durant le semestre et les vacances d’hiver montrent que l’organisation est un cadidat idéal pour être digne de financement de la VCSA.</p>', NULL),
(65, 'SPONSORS', 1, '<h1>Équipe Bana</h1>\n<img src="../../images/sponsors/TeamBana.jpg" class="sponsorImage">\n<p>L’équipe Bana, un groupe d’étudiants du fort Vanier, produit des sites web et des applications pour des petites armées à travers Westeros en utilisant les connaissances et les compétences qu’ils ont acquises dans le programme de science et technologie des ordinateurs. Leur financement ainsi que leur expérience ont été éssentiels à cette grande guerre.  </p>', NULL),
(66, 'SPONSORS', 1, '<h1>Rona Pierrefonds</h1>\n<img src="../../images/sponsors/Rona.jpg" class="sponsorImage">\n<p>RONA L’entrepôt Pierrefonds est ouvert en 2007 et depuis ce temps, il a répondu aux besoins de rénovations de la communauté à partir de son emplacement au 3933 Boul. St Charles, Pierrefonds. RONA est votre arrêt tout-en-un pour les matériaux de construction et les produits de rénovation domiciliare. </p>', NULL),
(67, 'JOURNALISM', 0, '<h1>Early Progress</h1>\n<p>The beginning of any great website start with great plans. With the theme of Game of Thrones in mind, the team bounced back ideas and concepts in a ice breaker  meeting, and produced many promising sketches of webpage looks. A key idea is that the introduction page was to resemble the grandiose Ice Wall in Game of Thrones. With a zoom function after the language selection, this would reveal the map of our own rendition of Westeros, the mainland in Game of Throne. This page would require exhaustive research in 3D animation and its insertion into the website code, which is where the members first decided to work on.</p>', 'WEB'),
(68, 'JOURNALISM', 0, '<p>After studying last year’s website for inspiration and coding examples, a member of the web team started working in 3D animations for the website. It was quickly realised that thinking of ways to make the website follow the theme of Game of Thrones and to make amazing and accurate use of its terminology would be extremely difficult. Members of the website team also encountered some difficulties in learning how to use the program “Blender”.</p>\n<p>Since some web team members were in their first year in cegep, the familiarization with web programming was expected to be a great challenge. Past web members, now accomplished programmers, held tutorial sessions about crucial components of website design and introductions to programming languages. The first year members spent the main bulk of 2015 on different facets of the coding language. The team photographer took headshots for the bios, which marks the first step in the journalism journey.</p>', 'WEB'),
(69, 'JOURNALISM', 0, '<h1>Winter Break</h1>\r\n<p>During the break (work time for Robotics!), many pictures for the gallery were taken and this brought about the thrilling task of sorting through all of the blurry pictures that are irrelevant to the competition. During this time, the actual coding and creation of the website began to run a lot more smoothly given that the members began to become more and more acquainted with Blender. At the same time, they began to conduct research on the other programming languages, such as C++ and JavaScript in order to help make the website interactive. The website’s framework is tested on an iPad to ensure that it can be accommodated on different types of devices.</p>', 'WEB'),
(70, 'JOURNALISM', 0, '<p>To facilitate communication and maintain a good pace of work, the codes were uploaded to GitHub, a social network dedicated to coding and shared projects. Each member had their assigned branch of the website to work on, with deadlines and details of each task clearly displayed on the main GitHub page. </p>\r\n<p>Journalism wise, while the journals of each team had to be completed little by little, considerable progress was made on the “fixed” pages, such as the description of Vanier college and the explanation of the competition rules. Members with Game of Throne knowledge edited those pages to mix in medieval flavor and the particular charm of the fantasy universe in question. The French translations of those available English pages were brought to completion as well, with the journalism team’s valiant efforts to include accurate French Game of Throne terminology. </p>', 'WEB'),
(71, 'JOURNALISM', 0, '<h1>Beginning of the Winter Semester</h1>\r\n\r\n<p>Upon returning to school, the ball really started to get rolling on the website team. Journalism began to get everything organised and started making tangible advances to the team journals. </p>\r\n\r\n<p>Andrew Hanichkovsky was appointed as the new leader of the team.</p>', 'WEB'),
(72, 'JOURNALISM', 0, '<h1>Final plans</h1>\r\n<p>The home page shifts from a map of Westeros, as the team initially intended, to an interactive throne room. The design includes the original layout of the Game of Throne room, with clickable banners of the four main House (team), which are also featured on the kiosk. </p>\r\n<p>The new challenge of this year’s Web team is to produce a powerful website that will be compatible to most devices. The journals will be displayed in an ancient tome acting as a flippable online reader, which we have modified from a flip magazine program. The integration of the program into the website code produced a few CSS bugs, but nothing major to require the removal of the program. Also, most of the pages would be equipped of a parallax background image reacting to phone gyroscope movement. </p>', 'WEB'),
(73, 'JOURNALISM', 0, '<img src="../../images/journalism/web/andrew.jpg" class="webImage">', 'WEB'),
(74, 'JOURNALISM', 0, '<p>The crunch hit hard, but with dedication, coffee and adrenaline, not even winter can defeat the coding team. </p>', 'WEB'),
(75, 'JOURNALISM', 1, '<h1>Le tout début:</h1>\r\n\r\n<p>Le début de tout site internet commence avec de bonnes idées. Avec le thème de Game of Thrones en tête, l’équipe responsable du site web a conçu plusieurs croquis potentiels. L’idée qui est ressortie le plus est celle où la page d’introduction ressemblerait au mur de glace imposant et marquant de la série télévisée Game of Thrones. Avec une fonction de zoom après la sélection de langue, ce mur révélera la terre de Westeros (place fictive dans l’Univers de Game of Thrones). Cette page requierera une recherche exhaustive portant sur l’animation 3D et l’insertion de celle-ci dans le code du site web. Cette page sera attaquée en premier par les membres du site web.</p>', 'WEB'),
(76, 'JOURNALISM', 1, '<p>En s’inspirant du site web de l’année passée et en voyant les exemples de codages, un membre de l’équipe a commencé à travaille sur l’animation 3D pour le site web. L’équipe réalise aussitôt qu’il sera extrêmement difficile à trouver des idées qui suivront le thème de Game of Thrones au pied de la lettre. De plus, plusieurs membres de l’équipe ont eu plusieurs difficultées à apprendre et à utiliser le programme ‘’Blender’’.</p>', 'WEB'),
(77, 'JOURNALISM', 1, '<h1>Le Congé d’Hiver</h1>\r\n\r\n<p>Durant le congé (pour le club de robotique, la période de travail), plusieurs dizaines de photos de l’équipe à l’épeuve ont été pris pour la galerie. En conséquence, l’équipe du journalisme a dû trier péniblement toutes les photos floues et mal prises. </p>\r\n\r\n<p>Pendant ce temps, les membres maîtrisent graduellement le programme « Blender » et ainsi le codage du site Web progresse à pas réguliers. Une portion de l’équipe débutent la recherche sur d’autres langages de programmation, tels « C++ » et « Javascript » afin d’améliorer l’interactivité du site Web. Pour faciliter la communication et maintenir un rythme de travail régulier, tout codage s’effectue sur « GitHub », un réseau social dédié à la programmation et aux projets collectifs. Chaque membre retrouve leur branche de code attribuée et les détails de leurs tâches clairement affichés sur la page principale de « GitHub ». </p>', 'WEB'),
(78, 'JOURNALISM', 1, '<p>Enfin, la charpente du site est testé sur un IPad de sorte à assurer sa compatibilité sur de différents appareils. </p>\n<h1>Début du semestre d’hiver </h1>\n\n<p>Dès le retour au cégep, l’équipe du Web affronte la programmation du site en plein force. L’équipe du journalisme débute à organiser le contenu produit à date et à remplir les journaux de bord de chaque équipe. Un nouveau capitaine a été assigné.</p>', 'WEB'),
(79, 'JOURNALISM', 1, '<h1>Plans finaux</h1>\r\n<p>La page d’accueil se transforme de la carte de Westeros, que nous avions initialement planifiée, à une version interactive de la salle de trône. Cette nouvelle conception provient de la série télévisée de « Game of Throne », mais elle inclut aussi quatre bannières cliquables, qui se figurent aussi dans le kiosque.</p>', 'WEB'),
(80, 'JOURNALISM', 1, '<p>Le nouveau défi de l’équipe Web 2016 est de produire un site Web puissant et compatible sur la plupart des appareils sur le marché. Les journaux seront affichés dans un tome ancien servant de lecteur en ligne. Ce dernier provient d’un programme de magazine digitalisé que nous avons modifié. L’integration de ce programme au code du site Web a produit quelques problèmesde CSS, mais ils ont tous été fixés. Enfin, la plupart des pages seront équippées d’image d’arrière-plan parallaxe, qui réagira au mouvement gyroscope des appareils mobiles.</p>', 'WEB'),
(81, 'JOURNALISM', 1, '<img src="../../images/journalism/web/andrew.jpg" class="webImage">', 'WEB'),
(82, 'JOURNALISM', 1, '<p>Les dernier jours de travail peuvent être dures, mais avec determination, cafféine et adrénaline, rien n’est impossible pour notre équipe!</p>', 'WEB'),
(83, 'JOURNALISM', 0, '<h1>Last Year - Tron </h1>\r\n<p>Last year’s kiosk was a total success. Tron Robotics was like another world with advanced technology. This year, however, the theme is Game of Thrones and we must go 12 000 years backward, during the time period of its universe. Therefore, a lot of modifications have been made. First, we repainted the wood panels from last year, but we kept Vanier’s logo on it with blue tape. Retouch work had to be done to compensate for the paint peeled off by the tape.</p>', 'KIOSK'),
(84, 'JOURNALISM', 0, '<h1>Winter Break Progress</h1>\r\n\r\n<p>The bulk of the winter break was spent on the literal foundation of the kiosk: the wall panels. Only dark, blood-stained brick walls could fit the dynamics of Game of Thrones. Many panels were needed. The captain brought styrofoam. During several days, the kiosk team as well as many helpers sculpted the styrofoam into the shape of a battered brick wall. Realism was one of, if not the most important factor of this year’s theme. All surface required 3 coats of paint: the black base layer, a red coating to set in the dark, bloody mood of an universe centered on war and politics, and finally, a silver layer to top the battered granite wall effect the kiosk team intended to achieve. After they have been painted, the walls looked like part of Vanier Robotics’ room and possibly, the worn facade of an ancient castle. The making of the walls were long but in the end it all paid off.</p>', 'KIOSK'),
(85, 'JOURNALISM', 0, '<h1>Progress in January </h1>\r\n<p>With the new semester, new projects took place in the kiosk chantier. Materials are ordered to begin the construction of the windows. Each section of the kiosk was already meticulously planned.</p>\r\n<p>The kiosk team runs smoothly, with no major disputes and respectable time management.</p>', 'KIOSK'),
(86, 'JOURNALISM', 0, '<p>-(2x) 32"x48" 3mm Acrylite > Article #55375006</p>\r\n\r\n<p>-(3x) 12\'X1"x1" *or slightly larger* solid wood non treated</p>\r\n\r\n<p>-(2x) 5m Led light strips > Article #33785356</p>\r\n\r\n<p>-(16x) L-Bracket 4 hole non braced type (might have some left over after done the windows)</p>\r\n\r\n<p>-(2x) box of 3/8" square or philips head screws </p>\r\n\r\n<p>-(enough to cover 2\'x4\' window backs) thin white poster board from dollarama</p>\r\n\r\n<p>- (1x) tube of PL adhesive > Article #0040005</p>\r\n \r\n<p>\r\n(sample of kiosk shopping list)\r\n</p>', 'KIOSK'),
(87, 'JOURNALISM', 0, '<h3>Description of the kiosk:</h3>\r\n\r\n<h1>Throne room:</h1>\r\n\r\n<p>The concept of the kiosk is centered around the throne room in the TV show, with dark walls, tall stained-glass windows, the famous Iron throne and enough dramatic flair to start wars. The objective was to maintain an authentic Game of Throne feel, while mixing in touches of Vanier robotics. </p>\r\n', 'KIOSK'),
(88, 'JOURNALISM', 0, '<img src="../../images/journalism/kiosk/throne.jpg" class="kioskImage">', 'KIOSK'),
(89, 'JOURNALISM', 0, '<h1>Stained-glass windows</h1>\r\n<p>The TV show throne room had a regal-looking stain glass piece atop the Iron Throne. Of course, as it is custom in Vanier Fort, the Robotics throne kiosk would have two. The design is based on the original prop in the show, but clever arrangements had to be made before the idea can be realized, since real stained glass requires material, tools, time and experience the team can’t reasonably obtain. The stained glass would be replaced with painted Plexiglas and lead tape would imitate soldering. LED lights would shine through the windows to both highlight the colors of the glass and offer a good lightning source in the Throne Room. A set of 2 panes of 2x4 feet would adorn the throne. This pane sitting by itself already looks stunningly like the real thing!</p>', 'KIOSK'),
(90, 'JOURNALISM', 0, '<img src="../../images/journalism/kiosk/glass.jpg" class="kioskImage">\n<p>Photograph: Ariana Dawn Gagnon</p>', 'KIOSK'),
(91, 'JOURNALISM', 0, '<h1>Throne</h1>\r\n<p>Connoisseurs in Game of Throne or not, the fact remains that the Iron Throne is the very symbol of the saga. It represents the glorious tales of the Westeros kingdom and hence, the construction of Vanier’s throne must be treated just as seriously. First, all throne requires a sturdy framework, just as how every kingdom must be built on a solid base. No nails or plank amiss! Next, the details of the throne are to be carved in styrofoam, painted, and attached to the main work. Every little piece of history, carefully collected, constitutes the glory of the empire. </p>', 'KIOSK'),
(92, 'JOURNALISM', 0, '<p>However, every kingdom throughout history has its own signature: while the theme must be deeply felt in the final result, Vanier Robotics must add a touch of its own! In fact, instead of the unsheathed swords in the original Iron Throne, the Vanier throne will be made out of gears and allen keys. The carving and building work of the throne will need vigorous work and ample of time, but we hope we can present to the competition a memorable piece of our 2015-2016 Robotics team.</p>', 'KIOSK'),
(93, 'JOURNALISM', 0, '<img src="../../images/journalism/kiosk/table.jpg" class="kioskImage">', 'KIOSK'),
(94, 'JOURNALISM', 0, '<h1>Banners</h1>\n<img src="../../images/journalism/kiosk/banners.jpg" class="kioskImage">\n<p>(caption: Guess which team is which!) </p>\n\n<p>The banners were created from several overlapped vector art pieces, Photoshop and mad skills by Massimo Triassi.\n</p>', 'KIOSK'),
(95, 'JOURNALISM', 0, '<p>Game of thrones has a characteristic noble House system, which we had translated into the teams of Vanier Robotics. Each team has its own house name, colors, sigil, motto and eventually, banners. In the context of the story, those banners have critical significance to the image of a Noble family. Hence, those four banners will be printed on fabric and displayed in the front of the kiosk. The sigils will also feature on this year’s Robotics T-shirts. Respectively, they represent web, build, kiosk and video (did you associate the banners with the right teams?). \r\n</p>', 'KIOSK'),
(96, 'JOURNALISM', 1, '<h1>L’an dernier - Tron </h1>\r\n<p>Le kiosk l’an dernier fut un succès sans équivalent. Le club de robotique de Vanier s’était propulsé vers le monde futuriste de Tron. Par contre, cette année, le thème de Games of Thrones nous rapporte jusqu’à 12 000 ans en arrière, là où toute cette technologie avancée n’existait pas. Donc, il a fallu faire nombre de modifications au kiosque. Tout d’abord, l’équipe s’occupant du kiosk a repeint les panneaux de bois de l’an dernier tout en conservant le logo de Vanier dessus.</p>', 'KIOSK'),
(97, 'JOURNALISM', 1, '<h1>Progrès pendant les vacances d’hiver</h1>\r\n\r\n<p>La majorité du temps à été utilisé sur finir les panneaux du kiosk. Seulement des murs de briques sombres et sanglants peuvent rentrer dans le thème de Game of Thrones. Nous avons besoin de plusieurs panneaux. Utilisant le styrofoam que le capitaine nous avait acheté, l’équipe de kiosk et plusieurs aides se mirent au travail pour sculpter nos beaux murs de briques. Le réalism était un de nos facteurs les plus importants cette année. Chaque surface a requis 3 couches de peinture: une couche noire de base, ensuite une couche de rouge profond pour mettre un peu l’atmosphère finalement une couche d’argent pour le gris profond du granit Après avoir été peint, les murs ressemblaient a des murs d’un château ancien légitime. C’était un processus long et épuisant, mais qui en a finalement valu la peine.</p>', 'KIOSK'),
(98, 'JOURNALISM', 1, '<p>Malheureusement, l’accumulation de tâches inaccomplies a été repoussé à deux mois avant le début de la compétition, ce qui pourrait prouver à être très difficile à rattraper sans plus de mains aidantes. </p>\r\n\r\n\r\n<h1>Progrès pendant janvier</h1>\r\n\r\n<p>Avec l’arrivée de la nouvelle semestre, de nouveaux projets débutent au chantier du kiosque. Les materiaux sont commendés pour la construction des fenêtres. En effet, chaque section du kiosque était déjà attentivement planifiée.</p>\r\n<p>L’équipe du kiosque travaille sérieusement, sans disputes et retards majeures. </p>', 'KIOSK'),
(99, 'JOURNALISM', 1, '<p>-(2x) 32"x48" 3mm Acrylite > Article #55375006</p>\r\n\r\n<p>-(3x) 12\'X1"x1" *peut être plus large* bois solide non-traité\r\n</p>\r\n<p>-(2x) 5m (DEL) bandes lumineuses > Article #33785356</p>\r\n\r\n<p>-(16x) étriers (4 trous, non-attaché) (possiblement en extra)\r\n</p>\r\n<p>-(2x) boîte de clous (3/8") </p>\r\n\r\n-(assez grand pour couvrir le dos des fenêtres 2’x4’) tableau de présentation blanc de Dollarama</p>\r\n\r\n<p>- (1x) tube d’adhésif de polyuréthane > Article #0040005</p>\r\n\r\n<p>(exemple de liste d’achat)</p>\r\n', 'KIOSK'),
(100, 'JOURNALISM', 1, '<h1>Description du kiosk:</h1>\r\n\r\n<h3>Salle de trône:</h3>\r\n\r\n<p>L\'idée du kiosque gravite autour de la salle de trône vue dans la série télévisée, avec ses murs sombres, ses larges fenêtres, son fameux Trône de Fer et une atmosphère dramatique à souhait. L’objectif du kiosque est de retenir l’essence de « Game of Throne », tout en ajoutant une touche de Robotique Vanier à la pièce.</p>', 'KIOSK'),
(101, 'JOURNALISM', 1, '<img src="../../images/journalism/kiosk/throne.jpg" class="kioskImage">', 'KIOSK'),
(102, 'JOURNALISM', 1, '<h1>Fenêtres à vitraux</h1>\r\n\r\n<p>Au-dessus du Trône de fer que l’on retrouve dans la dite série télévisée s’y retrouvait un vitrail solennel . Bien sûr, puisque nous faisions partie du Fort Vanier, le kiosque de Robotique en a besoin de deux vitraux.  Leur conception est basée sur les fenêtres originales de l’émission, mais des arrangements devront être faites pour réaliser cette partie du kiosque, puisque la réalisation d’un vrai vitrail a besoin de matériaux, de moyens, du temps et de l’expérience dont l’équipe ne peut obtenir dans le cadre de la compétition. Le verre voloré doit être remplacé par du Plexiglas et du ruban de plomb imite la soudure. La lumière de DEL traversera les fenêtres en surlignant les magnifiques couleurs des vitraux, tout en constituant une bonne source d’éclairage pour la salle de Trône. Une série de deux vitres ayant une dimension de 2X4 pieds décoreront le trône. </p>', 'KIOSK'),
(103, 'JOURNALISM', 1, '<img src="../../images/journalism/kiosk/glass.jpg" class="kioskImage">', 'KIOSK'),
(104, 'JOURNALISM', 1, '<h1>Le trône</h1>\r\n\r\n<p>Que vous connaissiez Game of Throne ou pas, il faut avouer que le Trône de Fer est le symbole de la saga. Ce dernier représente des légendes glorieuses du Royaume Westeros. En conséquence, la construction du trône de Vanier doit être pris avec la plus grande considération. D’abord, tout trône nécessite une structure robuste, tout comme le fait que chaque royaume doit être basé sur une base solide. Interdiction de manquer une seule planche ou un seul clou! Ensuite, les détails du trône doivent être sculptés dans de la styromousse, peints attentivement, et attachés avec la pièce centrale. La gloire de l’empire est formée par l’assemblement de chaque petite pièce de l’histoire. </p>', 'KIOSK'),
(105, 'JOURNALISM', 1, '<p>Par contre, chaque royaume au long de l’histoire a sa propre signature: malgré que le thème doit ressortir de notre produit final, l’équipe robotique de Vanier doit aussi laisser sa trace! En effet, au lieu des épées dégainées du Trône de Fer, le Trône de Vanier sera constitué de engrenages et des clés Allen. La sculpture et la construction du Trône auront besoin d’efforts vigoureux et de temps en masse, mais nous esperons que, malgré ces difficultés, nous pourrions présenter à la compétition une pièce mémorable de l’équipe Robotique 2015-2016.</p>', 'KIOSK'),
(106, 'JOURNALISM', 1, '<img src="../../images/journalism/kiosk/table.jpg" class="kioskImage">', 'KIOSK'),
(107, 'JOURNALISM', 1, '<h1>Bannières</h1>\n<img src="../../images/journalism/kiosk/banners.jpg" class="kioskImage">\n<p>(Devinez la bannière de chaque équipe!)<p>\n\n\n\n<p>Les bannières sont créées avec plusieurs images vectorielles chevauchées, « Photoshop » et beaucoup, beaucoup de talent par Massimo Triassi.</p>', 'KIOSK'),
(108, 'JOURNALISM', 1, '<p>La franchise « Game of Throne » possède un système de Maisons nobles dont nous avions intégré dans le kiosque. Chaque sous-équipe a son propre nom de maison, couleur, sigil, devise et eventuellement, bannières. Dans le contexte de la saga, ces bannières ont une signification particulière chez les Familles nobles. Pour cette raison, nos quatre bannières seront imprimées sur des toiles et exposées à l’avant du kiosque. Les sigils seront aussi présents sur le T-shirt de l’équipe. En ordre de gauche à droite, ces bannières appartiennent à l’équipe de Web, du robot, du kiosque et du vidéo. Les avez-vous bien associées? </p>\r\n<p>Les sigils sont créés en s’inspirant des œuvres d’art et dessinés grâce à des talents de Photoshop de l’équipe.</p>', 'KIOSK'),
(109, 'JOURNALISM', 0, '<h1>Video Team</h1>\r\n\r\n<p>Video process. How did you write the script, the filming process, what programs did you use to edit, difficulties, pictures, anecdotes...</p>', 'VIDEO'),
(110, 'JOURNALISM', 0, '<p>Mostly the script was written in a program called Celtx, which makes formatting your script quick and simple so that writers can get to the creative side of the script without worrying about the nitty gritty. A lot of the ideas for the script were based on the same formula as last years video, and for several reasons. For starters, last year’s formula just works well, hero gets teleported/time travels to the world in which our theme is based and he must play a game to escape. Another reason is that a larger, overarching story can be set in motion with this format, and in fact it has been. This way, all of our videos from now on can all feed into each other creating one long story that could continue for as long as the CRC hosts a robotics competition. </p>', 'VIDEO'),
(111, 'JOURNALISM', 0, '<img src="../../images/journalism/video/gaze.jpg" class="videoImage">\n<p>Contrary to popular belief, this is actually how video team stares at a screen while they work!</p>', 'VIDEO');
INSERT INTO `book` (`id`, `book`, `lang`, `content`, `subpage`) VALUES
(112, 'JOURNALISM', 0, '<p>A lot of the filming processes couldn\'t be done without the great team we’ve assembled this year. With so many dedicated members, everyone was able to focus on their own jobs and the whole operation ran more smoothly because of it. With 2 hard-working cameramen, an external sound operator, light technician, gaffers, and even our very own slate technician, the whole filming process felt very efficient and was as close to a real film set as we could get with our resources.</p>', 'VIDEO'),
(113, 'JOURNALISM', 0, '<img src="../../images/journalism/video/alexReaves.jpg" class="videoImage">', 'VIDEO'),
(114, 'JOURNALISM', 0, '<p>After the filming came the editing, for which we used premier pro. Editing was quite a breeze, the real difficulty came when I had to cut my initial edit from 8 ½ minutes to 5 minutes, and it\'s for that reason that we’re obviously going to have a director\'s cut released along with the condensed version. </p>', 'VIDEO'),
(115, 'JOURNALISM', 0, '<img src="../../images/journalism/video/vfx.jpg" class="videoImage">\n<p>Every impressive VFX is preceded by trials…</p>\n\n<p>Along with editing, VFX also had to be done. This year, we wanted a lot of practical effects but we also wanted some cool CGI so the space tunnel effect, for the time travel sequence, was born. It is supposed to resemble the slit scan effect in “2001: A space odyssey”, but also took some cues from GMUNK, a famous visual effects designer and artist. </p>', 'VIDEO'),
(116, 'JOURNALISM', 1, '<h1>Équipe Video</h1>\r\n<p>processus de la vidéo . Comment avez-vous écrit le scénario, le tournage , quels programmes avez-vous utilisé pour éditer , les difficultés, photos, anecdotes ...</p>', 'VIDEO'),
(117, 'JOURNALISM', 1, '<p>La plupart des scénarios est écrit dans un programme appelé Celtx, ce qui a rendu la mise en forme du script simple et rapide. Les écrivains ont donc pu se rendre à l\'aspect créatif de l\'écriture sans se soucier des détails techniques. Un grand nombre d’idées pour le script suivait la même formule que la vidéo de l’année passée et ce, pour plusieurs raisons. Tout d’abord, la forme générale de la dernière année fonctionnait plutôt bien: le héros voyage/se fait téléporter dans le temps pour arriver dans le monde de notre thématique et ce dernier doit participer à un jeu afin de s’échapper. Aussi, puisque les vidéos peuvent s’enchaîner de cette manière, chacun d’eux contribue dorénavent à une série d’histoires qui pourrait se poursuivre tant et aussi longtemps que la CRC organise la compétition de robotique.\r\n</p>', 'VIDEO'),
(118, 'JOURNALISM', 1, '<img src="../../images/journalism/video/gaze.jpg" class="videoImage">\n<p>Contrairement à la croyance populaire , c\'est en fait la façon dont l\'équipe vidéo regarde un écran pendant qu\'ils travaillent !</p>', 'VIDEO'),
(119, 'JOURNALISM', 1, '<p>Quant à la technique, une grande partie du processus de tournage n’aurait pas été réalisée sans la brillante équipe que nous avons rassemblée cette année, avec autant de membres dévoués. En effet, tous et chacun se concentrait sur leurs propres tâches, permettant à l’ensemble de l’opération d’avancer lentement mais sûrement. Avec deux cadreurs dédiés à leur travail, un opérateur de son externe, un technicien de lumière, un chef-électricien, et même notre propre claquiste, l’ensemble du processus de tournage fut très efficace et nous avons fait de notre mieux pour créer un plus professionnel plateau de tournage possible afin d’obtenir la meilleure qualité que nouspouvons atteindre à notre niveau.</p>', 'VIDEO'),
(120, 'JOURNALISM', 1, '<img src="../../images/journalism/video/alexReaves.jpg" class="videoImage">', 'VIDEO'),
(121, 'JOURNALISM', 1, '<p>Après le tournage vient le montage, réalisé en utilisant premier pro. L’édition s’était passé sans heurts. Le plus gros défi était pour moi de couper la vidéo de 8 ½ minutes à 5 minutes, et c’est la raison pour laquelle nous allons publier une version prolongée en plus de la version condensée. </p>\n\n<img src="../../images/journalism/video/vfx.jpg" class="videoImage">', 'VIDEO'),
(122, 'JOURNALISM', 1, '<p>Tous les effets spéciaux impressionnants sont précédés d’épreuves…</p>\r\n\r\n<p>En même temps que le montage, les effets spéciaux devaient aussi être ajoutés. Cette année, nous avons voulu ajouter divers effets « pratiques » en plus des images de synthèses impréssionnantes. Nous avons donc créé l\'effet d’un tunnel de l\'espace pour la séquence du voyage dans le temps. Nous nous sommes principalement inspirés de l\'effet « slit-scan » dans 2001: l\'Odyssée de l\'espace. De plus, des traces de GMUNK, un artiste et concepteur d’effects spéciaux renommé, se retrouve dans notre montage.\r\n</p>', 'VIDEO'),
(123, 'ROBOT', 1, '<h1>Aperçu du robot</h1>\r\n<p>Le jeu de cette année définit les attributs de notre robot. L’ensemble du robot doit se limiter à un cube large de 3 pouces et donc l’équipe doit amener leur assortiment de logiciel et matériel à son plein usage. Le robot doit être agile et capable d’effectuer des manipulations simples de nouilles de piscine. Nous avons choisi de modulariser les différents fonctions du robot. Les modules peuvent être catégorisées de la manière suivante: logique, propulsion, énergie et sous-systèmes fonctionnelles. </p>', 'BUILD'),
(124, 'ROBOT', 1, '<h1>Unité central</h1>\r\n<p>L’unité central constitue la structure supportant tous les sous-systèmes du robot. Il est construit d’un boîtier d’aluminium équippé d’un anneau protecteur intégré qui sert de squelette au robot. L’unité central est conçu pour supporter le poid de l’ensemble du robot en aluminium. Toutes les autres morceaux y seront attachés dessus.</p>', 'BUILD'),
(125, 'ROBOT', 1, '<h1>Sous-système du logiciel</h1>\r\n<p>Ceci forme le cerveau du robot. Sans celui-ci, le robot cesse de fonctionner. Il est composé d’un Microcontrôleur Cortex Vex. Ce dernier effectue toutes les opérations entrées-sorties, puisqu’il sert de relais électromécanique et d’interprète des données du circuit de contrôle électronique. Le microcontrôleur a été programmé avec un « RobotC », un environnement de développement propriétaire conçu pour le langage programmatique « RobotC ».</p>', 'BUILD'),
(126, 'ROBOT', 1, '<h1>Sous-système de propulsion</h1>\n<p>La propulsion du robot est fournie par un ensemble de sept roues omnidirectionnelle, alimentées par une paire de moteurs « Banebot » et un moteur de forage. Cette configuration laisse une grande liberté de rotation et elle inclut la capacité de mitraillage.</p>', 'BUILD'),
(127, 'ROBOT', 1, '<h1>Sous-système d’énergie</h1>\r\n<p>Le sous-système d’énergie permet au robot de fonctionner.Les circuits des robots de ce concours consistant d’un bas voltage en boucle pour la manette, des moteurs VEX , des détecteurs (or capteurs), et un voltage en boucle plus élevée pour être en mesure de faire fonctionner les moteurs plus puissants (comme ceux récupérés d’une perceuse sans fil). Notre design consiste de deux panneaux chauds et échangeables qui tiennent des piles, des manettes et la gestion professionnelle des câbles Victor SP (have no fucking idea how this makes sense) par les parties en aluminium du robot. L’éclairage et les effets sonores seront ajoutés vers la fin de l’assemblage et seront contrôlés par une autre manette.</p>', 'BUILD'),
(128, 'ROBOT', 1, '<h1>Sous-systèmes fonctionnelles </h1>\n<p>Ces parties correspondent aux fonctionnalités du robot. Chaque partie joue un rôle dans la réalisation des objectifs du jeu de cette année.<p>\n\n<p>Bras agrippeur</p>\n<p>Le bras agrippeur, comme son nom l’indique, agrippe les nouilles d’eau des pickets ou du sol pour les rentrer dans le panier de tri. Son articulation qui répare le bras en deux permet à l’extrémité manœuvrier de demeurer à un angle fixe de 45°.</p>', 'BUILD'),
(129, 'ROBOT', 1, '<p>Panier de tri</p>\r\n<p>Inspiré des trieuses de monnaie, notre panier à tri distribue des nouilles de piscine par grandeur dans trois compartiments différents. Les nouilles sont roulées vers les compartiments par dessus une planche de coroplast pré-coupée. La dispense des nouilles serait contrôlée par des actionneurs méchaniques.</p>\r\n\r\n<p>Fente d’éjection</p>\r\n<p>Cette partie s\'alignera à l\'une des cibles et poussera la nouille de piscine relâchée du bac de tri dedans.</p>\r\n\r\n<p>Mécanisme d’ascension</p>\r\n<p>Le mécanisme d’ascension de cette année est basé sur des poulies. Il peut apporter tous les sous-systèmes fonctionnels à une position plus élevée.</p>\r\n', 'BUILD'),
(130, 'ROBOT', 1, '<h1>Administration</h1>\n<p>Durant le congé de noël, une réunion importante entre membres du sous-équipe du robot s’est déroulée. En fait, plusieurs membres épouvaient de la difficulté à se mettre en accord sur certaines parties clés du robot et donc, des étincelles survolaient le bureau de robotique. À la suite d’une conversation respectueuse et constructive, ces membres ont atteint des compromis au sujet de leur opinions contradictoires et une promesse de fournir des efforts pour améliorer la communication. </p>\n<p>Pour éviter que ce problème se reproduise, un meilleur médium pour communiquer les décisions importantes et les dates limites, et une distribution plus raisonnable des pouvoirs de décision.</p>', 'BUILD'),
(131, 'ROBOT', 1, '<p>À partir de janvier, tous les tâches à accomplir sont affichées au tableau blanc et des photos du tableau seront publiés sur la page Facebook de l’équipe. The nouveau système devrait aider les membres de la première année à se trouver une tâche faisable à leur niveau et aider les membres plus expérimentés à mieux s’entendre avec l\'un et l\'autre.</p>\n\n<img src="../../images/robot/plans.jpg" class="robotImage">\n\n<p>Malgré que beaucoup de travail reste à faire, à cause du retard de livraison de certains matériaux, la réunion s’est terminée avec l’équipe prêt à s’attaquer à la liste de tâche avant la compétition. </p>', 'BUILD'),
(132, 'ROBOT', 0, '<h1>Robot Generalities</h1>\r\n<p>The game of this year\'s competition defines the specs of our robot. The whole package need to fit within a 3’ sided cube and make use of a limited set of hardware and software. The robot needs to be agile and capable of simple manipulations of pool noodles. We have elected to modularize the different functions of the robot. We can classify the modules as the logic, propulsion, power, and functional subsystems.</p>\r\n<h1>Mainframe</h1>\r\n<p>The mainframe is the core structure supporting all subsystems of the robot. It is a strong aluminium chassis with an integrated bumper ring that serve as the skeleton of the robot. It is designed to carry the heft of the mostly aluminum robot. All the other parts will be mounted to it.</p>', 'BUILD'),
(133, 'ROBOT', 0, '<h1>Logic Subsystem</h1>\r\n<p>This is the brain of the robot. Without it, the robot cannot function. It is composed of a VEX ARM® Cortex®-based Microcontroller. This part handles all of the IO operations in the robot as it serves as a relay and interpreter of the driver’s inputs. It is programmed using a RobotC, a proprietary development environment designed for the RobotC language.</p>\r\n<h1>Propulsion Subsystem</h1>\r\n<p>Propulsion is provided by a set of 7 omnidirectional wheels powered by a pair of Banebot motors and a drill motor. The configuration used allows great turning freedom and includes strafing capacity.</p>', 'BUILD'),
(134, 'ROBOT', 0, '<h1>Power Subsystem</h1>\r\n<p>The power subsystem is what keeps the robot running. The power circuit of CRC competition robots usually consists of a low voltage loop for the controller and VEX motors and sensors, as well as an elevated voltage loop to power more powerful motors, such as those salvaged from a cordless drill.  Our design consists of two hot-swappable panels holding batteries, Victor SP controllers and professional cable management through the aluminium parts of the robot. Lighting and sound effects will be added toward the final stages of assembly and will be controlled by a separate controller.</p>', 'BUILD'),
(135, 'ROBOT', 0, '<h1>Functional Subsystems</h1>\n<p>These parts provide the functionalities of the robot. Each part plays a role in accomplishing this year’s gameplay goals.</p>\n<p>Grabber Arm</p>\n<img src="{{img_path}}/grabArm.jpg" class=\'left\' width=\'200px\'>\n<p>The grabber arm, as the name says, grabs pool noodle sections off pegs or from the ground and feeds them into the sorting bin. It is a two part articulated arm that allows the manipulator end to remain at a fixed 45°.</p>', 'BUILD'),
(136, 'ROBOT', 0, '<p>Sorting Bin</p>\n<p>Inspired by coin sorters, the sorting bin sorts pool noodles by size into three separate bins by rolling them over a coroplast cutout. The release of pool noodles will be controlled by electronic actuators.</p>\n<p>Ejection Slot</p>\n<p>This part will align to any of the target and push in the pool noodle released by the sorting bin.</p>\n<p>Lift Mechanism</p>\n<p>This year’s lift mechanism is based on pulleys. It can bring all functional subsystems to a more elevated position.</p>', 'BUILD'),
(137, 'ROBOT', 0, '<h1>Administration</h1>\n<p>During winter break, an important meeting took place among a great portion of the team. In fact, many members had different ideas on the robot and hence, a few negative sparks were flying from some core members. With a respectful, constructive conversation, they reached a compromise for their difference in opinion and a promise of better communication terms for the foreseeable future.</p>\n<p>To avoid the recurrence of this issue, a few solutions were proposed to employ a better medium to communicate important decisions and deadlines, and maintain a fair distribution of decision power. </p>\n', 'BUILD'),
(138, 'ROBOT', 0, '<p>From January, all pending tasks are displayed on the main whiteboard and photos of it are also posted on the Facebook page. The new system should resolve the past issues of first year students willing to work but confused about what they can do, and core members disagreeing on decisions that have not been properly communicated throughout the team. </p>\n\n<img src="{{img_path}}/buildWhiteboard.jpg" height=\'270px\'>', 'BUILD'),
(139, 'ROBOT', 0, '<p>Although still a lot of work needs to be done on the robot, since shipping issues encumbered progress on certain sections of the team, the meeting concluded with a more optimistic team ready to tackle the pre-competition check-list.</p> \n\n<p>(steps in conception and construction, problems encountered, solutions, conception and prototype plans and drawings, final design plans and drawings, photos of robot)</p>', 'BUILD'),
(140, 'ROBOT', 0, '<h1>Prototype 1:</h1> <p>At first, the blitzcrank (grabbing arm) was supposed to be made of gears rotating and pulling the arm in the process. However, the gears are later replaced by chains. </p>\n\n<img src="{{img_path}}/proto1.png" width=\'350px\' alt="">', ''),
(141, 'ROBOT', 0, '<h1>Prototype 2:</h1><p> The inclined part of the arm (responsible of grabbing the tubes) is shortened to accommodate the size of the bin (it had to sit flush with the side of the bin. A shortened arm also decreases the mass of the robot. </p>\n\n<img src="{{img_path}}/proto2.jpg" width=\'260px\' alt="">\n<p>-The arm to pick up the tubes has two fixed parts: a 6” claw to pick up the tube and a 13” forearm to move the tube into the bin.  </p>', NULL),
(142, 'ROBOT', 1, '<h1>Prototype 1 </h1>\n<p>Au début, le Blitzcrank (bras saisissant ) devait être fait d\'engrenages, tournant et en tirant le bras dans le processus . Cependant , les engrenages sont ensuite remplacés par des chaînes.</p>\n\n<img src="{{img_path}}/proto1.png" width=\'350px\' alt="">', NULL),
(143, 'ROBOT', 1, '<h1>Prototype 2</h1>\n<p>La partie inclinée du bras (responsable de saisir les tubes) est raccourci à adapter à la taille de la corbeille (elle doit affleurer avec le côté de la caisse). Un bras raccourci diminue également la masse du robot.</p>\n\n\n<img src="{{img_path}}/proto2.jpg" width=\'260px\' alt="">\n\n<p>Le bras pour ramasser les tubes comporte deux parties fixes : 6 " griffe pour ramasser le tube et un 13 " avant-bras pour déplacer le tube dans la caisse.</p>', NULL),
(144, 'JOURNALISM', 0, '<h1>2016-01-07:</h1>\r\n<p>The arm to pick up the tubes is rebuilt to fit in the lift mechanism so it can rotate along the side of bin. The electronics part cannot be tested yet, because the cortex is missing. the bin. Although many pieces have to be taken apart, the process is quicker than before, since the design is already set.</p>\r\n<p>The bin itself is almost completed. </p>', 'BUILD'),
(145, 'JOURNALISM', 0, '<h1>2016-01-08</h1>\r\n<p>The same arm is taken apart for the 4th time, since a motor was missing from the arm.</p>\r\n<p>We had too many ideas on fixing the robot and creating it that we couldn’t choose which ideas to use.</p>\r\n<p>Materials needed to be scrapped since we had to change the proportions of the size that were already cut for the robot</p>\r\n<p>The robot is coming out as we expected, except it is not being build as fast as we’d like it to be.</p>', 'BUILD'),
(146, 'JOURNALISM', 0, '<h1>2016-01-15</h1>\r\n<p>An important meeting took place among a great portion of the team. The problems cumbering the progress of the robot have been discussed,with new solutions ready to be tested. A few negative sparks were flying from some core members and with a mature, constructive conversation, they reached a compromise for their difference in opinion and a promise of better communication terms for the foreseeable future. More importantly, with school starting, a few solutions were proposed to maintain a fair distribution of decision power and a better medium to communicate the important decisions and deadlines. Although still a lot of work needs to be done on the robot and shipping issues encumbers progress on certain sections of the team, the meeting concludes with a more optimistic team ready to tackle the pre-competition check-list. </p>', 'BUILD'),
(147, 'JOURNALISM', 0, '<h1>2016-01-17</h1>\r\n<p>New decisions about administration and planning have been made. Communication between team members is improved, and all pending tasks are displayed on the main whiteboard. Screenshots of the whiteboard are also posted on the Facebook page. The new system should resolve the past issues of first year students willing to work but confused about what they can do, and core members disagreeing on decisions that have not been properly communicated throughout the team. Also, 3 sub-captains with extensive knowledge of the robot and its progression are selected, to promote productivity while the build captain is away from the office. </p>', 'BUILD'),
(148, 'JOURNALISM', 0, '<img src="../../images/journalism/build/plans.jpg" class="buildImage">', 'BUILD'),
(149, 'JOURNALISM', 0, '<p>Build Experience: 8 AM, arriving without one idea about how a robot work, I was thrown into making a design for a pulling arm.  Fortunately, I was not alone, there were also two other people who also had no idea what were they doing. By sharing the task and suffer, we managed to find out something that could worked, we made a design… A second design because I made the mistake of putting the scale in inches as well as centimeters. A system of wheels and chain was supposed to “soak up” the cylinder.  Someone helped us to get familiarized with building stuff, then we got on fire and built a prototype. Sadly, the prototype did not fit the measurements of the robot. We then overcame the challenge of destroying our child. Three time we have rebuild the robot to finally get a good one.</p>', 'BUILD'),
(150, 'JOURNALISM', 0, '<p>Captain notes: the task is designed to have my team think of how to make something from scratch. This serves to show my team what it takes to design something that fits a given set of constraints. It\'s simple to follow instructions, but it\'s better to be able to follow your own instructions.</p>', 'BUILD'),
(151, 'JOURNALISM', 1, '<h1>2016-01-07:</h1>\r\n<p>Le bras pour ramasser les tubes est reconstruit pour tenir dans le mécanisme de levage, de sorte qu\'il peut tourner sur le côté du bac.  La partie électronique ne peut pas être encore testé , parce que le cortex manque le bac. </p>\r\n\r\n<p>Le bac lui-même est presque terminée.</p>\r\n', 'BUILD'),
(152, 'JOURNALISM', 1, '<h1>2016-01-08</h1>\r\n\r\n<p>Le même bras est démonté pour la 4ème fois , parce qu\'un moteur manquait dans le bras</p>\r\n\r\n<p>Nous avons eu de nombreuses idées sur la façon de construire le robot et nous ne pouvions pas choisir entre eux</p>\r\n\r\n<p>Des matériaux devait être mis au rebut car nous avons dû modifier les proportions de la taille qui ont déjà été coupés pour le robot</p>\r\n\r\n<p>Le robot sort comme on s\'y attendait, sauf qu\'il est de ne pas construire aussi vite que nous aimerions.</p>\r\n', 'BUILD'),
(153, 'JOURNALISM', 1, '<h1>2016-01-15</h1>\r\n<p>Une importante réunion a eu lieu entre une grande partie de l\'équipe . Les problèmes qui ont ralenti l\'avancement du robot ont été examinés , avec les nouvelles solutions prêtes à être testées. Quelques emotions négatifs volaient de certains membres de base et par une conversation mature, constructive. Ils ont trouvé un compromis pour leur différence d\'opinion et une promesse de meilleures conditions de communication pour l\'avenir prévisible. Plus important encore, avec départ de l\'école , quelques solutions ont été proposées pour maintenir une répartition équitable du pouvoir de décision et une meilleur moyen de communiquer les décisions et les échéances importantes . Bien qu\'il soit encore beaucoup de travail qui doit être fait sur ??les questions de robots et d\'expédition encombre progrès sur certains tronçons de l\'équipe , la réunion se termine par une équipe plus optimiste prêt à aborder la pré-compétition liste de contrôle.</p>', 'BUILD'),
(154, 'JOURNALISM', 1, '<h1>2016-01-17</h1>\r\n<p>De nouvelles décisions concernant l\'administration et la planification ont été faites . La communication entre les membres de l\'équipe est améliorée , et toutes les tâches en attente sont affichées sur le tableau blanc principale . Captures d\'écran de tableau blanc sont également affichés sur la page Facebook . Le nouveau système devrait permettre de résoudre les problèmes de dernières étudiants de première année prêts à travailler mais confus à propos de ce qu\'ils peuvent faire , et les membres de base en désaccord sur les décisions qui ne sont pas correctement communiquées avec tout l\'équipe. En outre, 3 sous- capitaines ayant une connaissance approfondie du robot et sa progression sont choisis , de promouvoir la productivité tandis que le capitaine de construction est loin du bureau .</p>', 'BUILD'),
(155, 'JOURNALISM', 1, '<img src="../../images/journalism/build/plans.jpg" class="buildImage">', 'BUILD'),
(156, 'JOURNALISM', 1, '<p>Acquérir de l\'expérience : 8 heures , arrivant sans aucune idée de comment fonctionne un robot , j\'a été jeté dans la prise de la conception d\'un bras de traction . Heureusement, je ne suis pas seul , il y avait aussi deux autres personnes qui avaient également aucune idée de ce qu\'ils faisaient . En partageant la tâche, nous avons réussi à trouver quelque chose qui pourrait fonctionner , nous avons fait un design ... Une seconde conception, car je fis l\'erreur de mettre l\'échelle en pouces ainsi que des centimètres . Un système de roues et de la chaîne était censé " absorber " le cylindre . Quelqu\'un nous a aidés à se familiariser avec la construction des choses , puis nous sommes arrivés a construire un prototype. Malheureusement , le prototype ne correspondait pas aux mesures du robot . Nous avons ensuite surmonté le défi de détruire notre enfant . Trois fois, nous aurons reconstruire le robot pour obtenir enfin un bon.</p>\n', 'BUILD'),
(157, 'JOURNALISM', 1, '\n<p>Note Capitaine : la tâche est conçu pour avoir mon équipe penser à la façon de faire quelque chose à partir de zéro . Cela sert à montrer mon équipe ce qu\'il faut pour concevoir quelque chose qui correspond à un ensemble donné de contraintes . Il est facile de suivre ces instructions, mais il vaut mieux être en mesure de suivre vos propres instructions.</p>', 'BUILD');

-- --------------------------------------------------------

--
-- Table structure for table `gallery`
--
-- Creation: Feb 07, 2016 at 05:06 AM
--

DROP TABLE IF EXISTS `gallery`;
CREATE TABLE IF NOT EXISTS `gallery` (
  `gal_id` int(11) NOT NULL AUTO_INCREMENT,
  `gal_img` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `gal_desc_FR` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `gal_desc_EN` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`gal_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Truncate table before insert `gallery`
--

TRUNCATE TABLE `gallery`;
--
-- Dumping data for table `gallery`
--

INSERT INTO `gallery` (`gal_id`, `gal_img`, `gal_desc_FR`, `gal_desc_EN`) VALUES
(1, 'AlexFilming.JPG', NULL, 'Team Captain Alex on set filming the time travel sequence!'),
(2, 'BuildArms.JPG', NULL, 'Members of buid team attempt to come up with a design for the grabber arm!'),
(3, 'BuildDemoSorting.JPG', NULL, 'Build Captain Zixin demonstrating his concept of the sorting bin.'),
(4, 'BuildDiscussSortingBin.JPG', NULL, ''),
(5, 'BuildLunchBreak.JPG', NULL, 'Members of build and Kiosk Captain take a lunch break'),
(6, 'DremelChris.JPG', NULL, 'Build team member Sto cuts away with a Dremel tool'),
(7, 'FateWeaverHarry.JPG', NULL, 'Team Faculty Coordinator Haritos gets into character as "The Fate Weaver."'),
(8, 'FinishedWalls.JPG', NULL, 'The 2 first panels of the Kiosk walls are complete.'),
(9, 'IssaKnightingAlex.JPG', NULL, 'Issa "Knighting" Captain Alex on the outdoor set of the video'),
(10, 'IssaSword.JPG', NULL, 'Issa trying to look menacing as he poses for a teaser photo.'),
(11, 'JournalismReview.JPG', NULL, 'Members of Journalism reviewing content from the 2015 website for inspiration.'),
(12, 'JournalismWorking.JPG', NULL, 'Journalism team hard at work.'),
(13, 'LearningHTML.JPG', NULL, 'Member of Web Team learning HTML'),
(14, 'PaintingWalls.JPG', NULL, 'Kiosk Team member painting the back of the Kiosk walls'),
(15, 'Soldering.JPG', NULL, 'A Member of the build team preps some wiring for the Robot'),
(16, 'SortingBin.JPG', NULL, 'An up-close shot of the sorting bin for the robot'),
(17, 'WallCarving.JPG', NULL, 'Kiosk Captain Ariana and Team Captain Alex carving out another kiosk wall'),
(18, 'WebDiscussion.JPG', NULL, 'Web Captain Andrew studying the feasability of WebGL'),
(19, 'WebRobThinking.JPG', NULL, 'Web Team member hard at work'),
(20, 'WebThinking.JPG', NULL, 'Members of Web and Video discussing some web features.');

-- --------------------------------------------------------

--
-- Table structure for table `language_lookup`
--
-- Creation: Feb 06, 2016 at 05:30 PM
--

DROP TABLE IF EXISTS `language_lookup`;
CREATE TABLE IF NOT EXISTS `language_lookup` (
  `lang_ID` int(11) NOT NULL AUTO_INCREMENT,
  `lang_Abreviation` char(2) CHARACTER SET utf8 NOT NULL,
  `lang_Name` varchar(10) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`lang_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Truncate table before insert `language_lookup`
--

TRUNCATE TABLE `language_lookup`;
--
-- Dumping data for table `language_lookup`
--

INSERT INTO `language_lookup` (`lang_ID`, `lang_Abreviation`, `lang_Name`) VALUES
(0, 'EN', 'English'),
(1, 'FR', 'French');

-- --------------------------------------------------------

--
-- Table structure for table `team_lookup`
--
-- Creation: Feb 06, 2016 at 05:31 PM
--

DROP TABLE IF EXISTS `team_lookup`;
CREATE TABLE IF NOT EXISTS `team_lookup` (
  `team_ID` int(2) NOT NULL,
  `team_Name` varchar(15) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`team_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Truncate table before insert `team_lookup`
--

TRUNCATE TABLE `team_lookup`;
--
-- Dumping data for table `team_lookup`
--

INSERT INTO `team_lookup` (`team_ID`, `team_Name`) VALUES
(0, 'Build'),
(1, 'Kiosk'),
(2, 'Web'),
(3, 'Video'),
(4, 'Mentor'),
(6, 'TeamCaptain');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--
-- Creation: Feb 06, 2016 at 05:29 PM
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(20) CHARACTER SET latin1 NOT NULL,
  `password` varchar(64) CHARACTER SET latin1 NOT NULL,
  `first_name` varchar(30) CHARACTER SET latin1 NOT NULL,
  `last_name` varchar(30) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `users_user_id_uindex` (`user_id`),
  UNIQUE KEY `users_username_uindex` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Truncate table before insert `users`
--

TRUNCATE TABLE `users`;
--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `username`, `password`, `first_name`, `last_name`) VALUES
(1, 'u3', 'fa074610667173c1d6e863930c2d2aee82a2323de25692ed36de4f87aeb3666f', 'Andrew', 'Hanichkovsky');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `bios`
--
ALTER TABLE `bios`
  ADD CONSTRAINT `bios_lang_id` FOREIGN KEY (`bio_Lang`) REFERENCES `language_lookup` (`lang_ID`),
  ADD CONSTRAINT `bios_team_id` FOREIGN KEY (`bio_TeamID`) REFERENCES `team_lookup` (`team_ID`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
